config/routes.rb
Rails.application.routes.draw do

resources :books
resources :rentals

devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'welcome/index'

  get 'get_info', to: 'books#get_info', path: "/books/new/get_info"

  root to: "pages#home"

get 'pages/home'
get 'pages/about'
get 'books/isbn'

end

app/models/book.rb
class Book < ActiveRecord::Base



has_one :rental

    validates :title, :author, :manufacturer, :publication_date, :isbn, presence: true

belongs_to :user 


end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/rental.rb
class Rental < ActiveRecord::Base
  belongs_to :Book
  belongs_to :User
  belongs_to :Log
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

# 以下を追加
  has_many :rentals
  has_many :books
  validates :name, presence: true


def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    #user.image = auth.info.image # assuming the user model has an image
  end
end

 def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

before_action :configure_permitted_parameters, if: :devise_controller?


#protect_from_forgery with: :exception


# 以下を追加
#rescue_from CanCan::AccessDenied do |exception|
#redirect_to root_url, :alert => exception.message
#end

protected

def configure_permitted_parameters
 devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :role, :name) }
  devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :role, :name) }
end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :set_book, only: [:show, :edit, :update, :destroy]

before_action :authenticate_user!

respond_to :js, :json, :html




  def index
    @books = Book.all.order("created_at DESC")

  end


  def show


  end

  def new
    @book = Book.new
  end

def search_book
@book = Book.all

end


   def get_info
  @book = Book.new
  @book.isbn = params[:isbn]

  require 'open-uri'
  require 'json'

    #AWS
    # Amazon::Ecs.debug = true
    # res = Amazon::Ecs.item_search(params[:isbn],
    #      :search_index   => 'Books',
    #      :response_group => 'Medium',
    #      :country        => 'jp'
    #    )
    # info = {
    #   'Image' => res.first_item.get('MediumImage/URL'),      
    #   'Title' => res.first_item.get('ItemAttributes/Title'),
    #         'Author' => res.first_item.get('ItemAttributes/Author'),
    #         'Manufacturer' => res.first_item.get('ItemAttributes/Manufacturer'),
    #         'Publication_Date' => res.first_item.get('ItemAttributes/PublicationDate')
    #         }
    # render json: info

  
      params = {
        applicationId: ENV["RK_APPLICATION_ID"], 
        isbn: @book.isbn,
        format: "json"


        ###フォーム内のISBNを変数にAPIを叩く
        #isbn: isbn
      }

      # Prepare API request
      uri = URI.parse("https://app.rakuten.co.jp/services/api/BooksBook/Search/20130522")
      uri.query = URI.encode_www_form(params)

      #debug用にopen(uri).readの中身を吐き出す  
      Rails.logger.info open(uri).read

      # Submit request
      result = JSON.parse(open(uri).read)

      #Display results to screen
      #puts JSON.pretty_generate result

        info = {
        
        'Image' => result["Items"].first["Item"]["mediumImageUrl"],  
        'Isbn' => result["Items"].first["Item"]["isbn"],  
        'Title' => result["Items"].first["Item"]["title"],
        'Author' => result["Items"].first["Item"]["author"],
        'Manufacturer' => result["Items"].first["Item"]["publisherName"],
        'Publication_Date' => result["Items"].first["Item"]["salesDate"]
 

        }
         render json: info


    end


  def create
    @book = Book.new(book_params)
    @book.name = current_user.name
    if @book.save
      redirect_to books_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to books_path
    else
      render 'edit'
    end
  end

  def destroy
    # if @book.rental.nil?
    #   @book.destroy
    #   redirect_to books_path
    # else
    #   redirect_to books_path, notice: "その本は貸出中のため削除できません。"
    # end

    @book.destroy
    redirect_to books_path

  end

  private

    def book_params
      params[:book].permit(:title, :image, :author, :manufacturer, :publication_date, :isbn, :book_code, :name)
    end

    def set_book
      @book = Book.find(params[:id])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

 def contact
  end

  def home
    
  end

end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

def index
    @user = current_user
    @rentals = @user.rentals.all 
  end

 
  def new
    @book = Book.new
    @rental = Rental.new
  end

  def create
    @book = Book.find(params[:book].require(:id))
    if @book.Rental_id.nil?
      @rental = Rental.new(rental_date: DateTime.now)
      @rental.User = current_user
      @rental.Book = @book
      if @rental.save
        @book.increment(:rental_count)
        @book.Rental_id = @rental.id
        @book.save
        redirect_to rentals_path
      else
        render 'new'
      end
    else
      redirect_to new_rental_path, notice: "その本はすでに貸出中です。"
    end
  end

  def destroy
    @rental = current_user.Rentals.find(params[:id])
    @rental.Book.update(Rental_id: nil)
    @rental.destroy
    redirect_to rentals_path
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

 def bootstrap_devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
    count: resource.errors.count,
    resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h5>#{sentence}</h5>
      #{messages}
    </div>
    HTML

    html.html_safe
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/edit.html.erb
<h1>本の編集</h1>

<%= bootstrap_form_for(@book) do |f| %>
  <%= f.text_field :isbn %>
  <%= f.text_field :title %>
  <%= f.text_field :author %>
  <%= f.text_field :manufacturer %>
  <%= f.text_field :publication_date %>
  <%= f.text_field :book_code %>
  <%= f.primary "本を編集" %>
<% end %>

app/views/books/index.html.erb
<h1>蔵書一覧</h1>

<%= link_to "本の追加", new_book_path, :class => "btn btn-primary" %><br>

<hr>

<% if @books.any? %>
<table class="table table-bordered table-hover table-condensed">
  <thead>
     <tr class="info"><th>ID</th><th>Image</th><th>Titile</th><th>Author</th><th>Manufacture</th><th>Registered by</th><th>Release</th><th>Operation</th></tr>
  </thead>
  <tbody>
    <% @books.each do |b| %>
    <tr>
    <td><%= b.id %></td>
    <td class="text-center" ><%= link_to (image_tag(b.image)), b.image %></td>
    <td><%= b.title %></td>
    <td><%= b.author %></td>
    <td><%= b.manufacturer %></td>
    <td><%= b.name %></td>
    <td><%= b.publication_date %></td>
    <td width="230" align="center">
      
      <div class="btn-group">
        <%= link_to 'Show', book_path(b.id), class: "btn btn-info" %>
      <% if b.name == current_user.name%> 
        <%= link_to 'Edit', edit_book_path(b.id), class: "btn btn-success" %>
        <%= link_to 'Destroy', book_path(b.id), method: :delete, data: { confirm: "削除してもよろしいですか？" }, :class => "btn btn-danger" %>
      <% end %>
      </div> 

    </td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <h4>No data yet.</h4>
<% end %>

app/views/books/new.html.erb
<h1>本の追加</h1>
<div class="container" >
    <%= bootstrap_form_for(@book) do |f| %>
      <%= f.text_field :isbn %>
      <input class="btn btn-danger" type="button" id="info_search_button" value="検索">

<br>
<p> 写真からISBN情報を取り込む </p>
 <div id="container">
        <canvas width="320" height="240" id="picture"></canvas>
        <input id="Take-Picture" type="file" accept="image/*;capture=camera" />
        <p id="textbit"></p>
      </div>


      <%= f.text_field :image %>
      <%= f.text_field :title %>
      <%= f.text_field :author %>
      <%= f.text_field :manufacturer %>
      <%= f.text_field :publication_date %>
      <%= f.text_field :book_code %>

      <%= f.primary "本を追加" %>
    <% end %>

      <br>

      <br>
</div>

     


<%= javascript_include_tag "JOB" %>
<script type="text/javascript">
<!--
$(function () {
        var takePicture = document.querySelector("#Take-Picture"),
        showPicture = document.createElement("img");
        Result = document.querySelector("#textbit");
        var canvas =document.getElementById("picture");
        var ctx = canvas.getContext("2d");
       
        JOB.Init();
        JOB.SetImageCallback(function(result) {
          if(result.length > 0){
            var tempArray = [];
            for(var i = 0; i < result.length; i++) {
              tempArray.push(result[i].Format+" : "+result[i].Value);
            }
            Result.innerHTML=tempArray.join("<br />");
          

          //jQueryを使ってIDセレクタ #book_isbnにデータを入力
            var tempArrayib = [];
            for(var i = 0; i < result.length; i++) {
              tempArrayib.push(result[i].Value);
            }
          $("#book_isbn").val(tempArrayib.join("<br />"));
            

          }else{
            if(result.length === 0) {
              Result.innerHTML="Decoding failed.";
            }
          }
        });
        JOB.PostOrientation = true;
        JOB.OrientationCallback = function(result) {
          canvas.width = result.width;
          canvas.height = result.height;
          var data = ctx.getImageData(0,0,canvas.width,canvas.height);
          for(var i = 0; i < data.data.length; i++) {
            data.data[i] = result.data[i];
          }
          ctx.putImageData(data,0,0);
        };
        JOB.SwitchLocalizationFeedback(true);
        JOB.SetLocalizationCallback(function(result) {
          ctx.beginPath();
          ctx.lineWIdth = "2";
          ctx.strokeStyle="red";
          for(var i = 0; i < result.length; i++) {
            ctx.rect(result[i].x,result[i].y,result[i].width,result[i].height); 
          }
          ctx.stroke();
        });
        if(takePicture && showPicture) {
          takePicture.onchange = function (event) {
            var files = event.target.files;
            if (files && files.length > 0) {
              file = files[0];
              try {
                var URL = window.URL || window.webkitURL;
                showPicture.onload = function(event) {
                  Result.innerHTML="";
                  JOB.DecodeImage(showPicture);
                  URL.revokeObjectURL(showPicture.src);
                };
                showPicture.src = URL.createObjectURL(file);
              }
              catch (e) {
                try {
                  var fileReader = new FileReader();
                  fileReader.onload = function (event) {
                    showPicture.onload = function(event) {
                      Result.innerHTML="";
                      console.log("filereader");
                      JOB.DecodeImage(showPicture);
                    };
                    showPicture.src = event.target.result;
                  };
                  fileReader.readAsDataURL(file);
                }
                catch (e) {
                  Result.innerHTML = "Neither createObjectURL or FileReader are supported";
                }
              }
            }
          };
        }

      
     
        
       
        $('#info_search_button').click(function(){
        isbncode = $('#book_isbn').val()
        $.ajax({
            async:    true,
            url:      "/books/new/get_info/",
            type:     "GET",
            data:     {isbn: isbncode},
            dataType: "json",
            context:  this,
          success: function(data, textStatus, jqXHR){
                $("#book_image").val(data.Image) //# 画像
                $("#book_title").val(data.Title) //# タイトル
                $("#book_author").val(data.Author) //# 著者
                $("#book_manufacturer").val(data.Manufacturer) //# 出版社
                $("#book_publication_date").val(data.Publication_Date) //# 出版日
          }
      });
            }) 


 $('#info_search_button').click(
            function(){
          $('h1').text("書籍情報自動入力")
          });

});
//-->
</script>

app/views/books/show.html.erb
<h1>本の詳細</h1>

<table class="table table-bordered">
  <tbody>
    <tr>
    <td width="100", class="info">イメージ</td> <td><%= image_url @book.image %></td>
    </tr>
    <tr>
    <td width="100", class="info">タイトル</td> <td><%= @book.title %></td>
    </tr>
    <tr>
    <td width="100", class="info">著者</td> <td><%= @book.author %></td>
    </tr>
    <tr>
    <td width="100", class="info">出版社</td> <td><%= @book.manufacturer %></td>
    </tr>
    <tr>
    <td width="100", class="info">出版日</td> <td><%= @book.publication_date %></td>
    </tr>
    <tr>
    <td width="100", class="info">ISBN</td> <td><%= @book.isbn %></td>
    </tr>
    <tr>
    <td width="100", class="info">管理番号</td> <td><%= @book.book_code %></td>
    </tr>
        <tr>
    <td width="100", class="info">登録者名</td> <td><%= @book.name %></td>
    </tr>
  </tbody>
</table>

app/views/layouts/_header.html.erb
 <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/pages/home">Shariends</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            
            <li><%= link_to "蔵書一覧", books_path  %></li>
          </ul>
          <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "プロフィール変更", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to "サインアウト", destroy_user_session_path, :method => :delete%></li>
              </ul>
            </li>
          </ul>
          <% end %>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Booksearch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


</head>
<body>
<%= render 'layouts/header' %>


<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
TBD

app/views/pages/home.html.erb
<div class="jumbotron container">
  <h1>Shariends!</h1>
  
<% if user_signed_in? %>
  	<%= link_to "蔵書一覧",books_path ,  class: "btn btn-primary btn-lg" %>	
  		<% else %>
  	<%= link_to "Sign up", new_user_registration_path,  class: "btn btn-primary btn-lg" %>
  	<%= link_to "Log in", new_user_session_path, class: "btn btn-primary btn-lg" %>
<% end %>

</div>
  
<div class="homepage-hero-module">
    <div class="video-container">
        <div class="filter"></div>
        <video autoplay loop class="fillWidth">
            <source src= "https://s3-ap-northeast-1.amazonaws.com/sharedemo/Cloudy-water.mp4" type="video/mp4" />Your browser does not support the video tag. I suggest you upgrade your browser.
            <source src= "https://s3-ap-northeast-1.amazonaws.com/sharedemo/Cloudy-water.webm" type="video/webm" />Your browser does not support the video tag. I suggest you upgrade your browser.
        </video>
        <div class="poster hidden">
            <img src= "https://s3-ap-northeast-1.amazonaws.com/sharedemo/Cloudy-water.jpg" alt="">
        </div>
    </div>
</div>


<script>
$( document ).ready(function() {

    scaleVideoContainer();

    initBannerVideoSize('.video-container .poster img');
    initBannerVideoSize('.video-container .filter');
    initBannerVideoSize('.video-container video');

    $(window).on('resize', function() {
        scaleVideoContainer();
        scaleBannerVideoSize('.video-container .poster img');
        scaleBannerVideoSize('.video-container .filter');
        scaleBannerVideoSize('.video-container video');
    });

});

function scaleVideoContainer() {

    var height = $(window).height() + 5;
    var unitHeight = parseInt(height) + 'px';
    $('.homepage-hero-module').css('height',unitHeight);

}

function initBannerVideoSize(element){

    $(element).each(function(){
        $(this).data('height', $(this).height());
        $(this).data('width', $(this).width());
    });

    scaleBannerVideoSize(element);

}

function scaleBannerVideoSize(element){

    var windowWidth = $(window).width(),
    windowHeight = $(window).height() + 5,
    videoWidth,
    videoHeight;

    console.log(windowHeight);

    $(element).each(function(){
        var videoAspectRatio = $(this).data('height')/$(this).data('width');

        $(this).width(windowWidth);

        if(windowWidth < 1000){
            videoHeight = windowHeight;
            videoWidth = videoHeight / videoAspectRatio;
            $(this).css({'margin-top' : 0, 'margin-left' : -(videoWidth - windowWidth) / 2 + 'px'});

            $(this).width(videoWidth).height(videoHeight);
        }

        $('.homepage-hero-module .video-container video').addClass('fadeIn animated');

    });
}

</script>

app/views/rentals/index.html.erb
<h1>貸出中図書一覧</h1>

<%= link_to "本の貸出", new_rental_path, class: "btn btn-primary" %>

<hr>

<% if @rentals.any? %>
<table class="table table-bordered table-hover">
  <thead>
     <tr class="info"><th>#</th><th>タイトル</th><th>貸出日時</th><th>返却処理</th></tr>
  </thead>
  <tbody>
    <% @rentals.each_with_index do |r, i| %>
    <tr>
    <td><%= i+1 %></td>
    <td><%= r.Book.title %></td>
    <td><%= r.rental_date.in_time_zone('Tokyo') %></td>
    <td width="100" align="center">
      <%= link_to '返却', rental_path(r.id), method: :delete, data: { confirm: "この本を返却します。よろしいですか？" }, :class => "btn btn-danger" %>
    </td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <h4>No data yet.</h4>
<% end %>

app/views/rentals/new.html.erb
<h1>本の貸出</h1>

<%= bootstrap_form_for(@book, :url => rentals_path) do |f| %>
  <%= f.text_field :book_code %>
  <input class="btn btn-danger" type="button" id="search_button", value="検索">
  <b id="error_msg">  </b>
  <hr>
  <%= f.text_field :title, :readonly => true %>
  <%= f.text_field :author, :readonly => true %>
  <%= f.text_field :manufacturer, :readonly => true %>
  <%= f.text_field :id, :readonly => true %>
  <%= f.primary "貸出", id: "rental_button", disabled: "disabled" %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>